// <auto-generated />
namespace DomainRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtableuserurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableuserurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201612100609428_add-table-userurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
